# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd7c46db9cb34e95641f9d8cdb1143610097d6810edae1ffc949bf5c4c8c83b7ba8b3a2f048aed34e113739ed40a8708a376d3d8d9f96b3e5966a2569f86268a

test:
  secret_key_base: 74e9db6a8c888e0431ca5c62a4840e0407690dd5b5e2c22d78d3e523cf66c411cc20d5fc392f0c5d046063be45e44d14c82bc4dccb712e2950583f346760bb94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
